# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Amir Mohammad Babaei
subtitle: 'Computer Engineering M.Sc. Student @ Sharif University of Technology'
description: |
  I’m a computer vision researcher who enjoys turning tough visual problems into clean, reproducible solutions. I’m doing my M.Sc. at Sharif University of Technology in the Image Processing Lab (IPL), where I work at the intersection of generative models and super-resolution, lately exploring diffusion-based approaches for hard, blind settings. 

  Along the way, I’ve been lucky to learn from outstanding mentors. At IPL (advised by Prof. Shohreh Kasaei), I’ve built and evaluated models with care (tight ablations, clear baselines, and code that others can run). I also collaborated with Dr. Alireza Esmaeilzehi on image super-resolution ideas and kernel-estimation theory, which sharpened my taste for practical yet principled research.

  <b>What I work with.</b> PyTorch, diffusion/VAEs/GANs, BasicSR/KAIR/MMCV, Detectron, OpenCV, CUDA, Transformers; rigorous evaluation, dataset hygiene, experiment tracking, and readable research code. (If you’re building in these areas (or teaching them) I’m your person.)

  <b>What I’m aiming for.</b> I love collaborating on projects that sit where theory meets deployment: efficient generative models, blind SR, and multimodal vision tasks. If you’re exploring these topics, I’d love to connect.

  Links:
  — Lab: <a href='https://ipl.ce.sharif.edu/' target='_blank'>Image Processing Lab (IPL), SUT</a> · Advisor: <a href='https://scholar.google.com/citations?user=mvx4PvgAAAAJ&hl=en' target='_blank'>Prof. Shohreh Kasaei</a> · Collaborator: <a href='https://scholar.google.com/citations?hl=en&user=WAISKYYAAAAJ' target='_blank'>Dr. Alireza Esmaeilzehi</a>.

keywords:
author: Amir Mohammad Babaei
language: en
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://AmirMohamadBabaee.github.io
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tag
archive_dir: archives
category_dir: category
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
marked:
  prependRoot: true
  postAsset: true
  lazyload: true  # optional
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map: 

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: fengye

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: git@github.com:AmirMohamadBabaee/AmirMohamadBabaee.github.io.git
  branch: main
